[package]
name = "rust_boot"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.stage-1]
inherits = "release"
opt-level = "s"
lto = true
codegen-units = 1
debug = false
overflow-checks = false
